# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: nuget
    directory: "Projects/project.ad/"
    schedule:
      interval: "daily"
      time: "10:30"
    target-branch: main
    pull-request-branch-name:
      separator: "-"
    # reviewers:
    #   - "MRRSoft/znode-base-maintainers"
  - package-ecosystem: nuget
    directory: "Znode.NUGETcp/Engines/Znode.Engine.Taxes/"
    schedule:
      interval: "daily"
      time: "10:30"
    target-branch: main


    # reviewers:
    #   - "MRRSoft/znode-base-maintainers"

  - package-ecosystem: nuget
    directory: "statenode/APIGateways/Znode.Engine.APIGateways/"
    schedule:
      interval: "daily"
      time: "10:30"
      
    target-branch: main

    pull-request-branch-name:
      separator: "-"
    
  - package-ecosystem: nuget # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "10:30"
    pull-request-branch-name:
    target-branch: main

      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
