version: 2
updates:
  - package-ecosystem: nuget
    directory: "Projects/project.ad/"
    schedule:
      interval: "daily"
      time: "10:20"
    target-branch: main
    pull-request-branch-name:
      separator: "-"
    # reviewers:
    #   - "MRRSoft/znode-base-maintainers"
  - package-ecosystem: nuget
    directory: "Znode.NUGETcp/Engines/Znode.Engine.Taxes/"
    schedule:
      interval: "daily"
      time: "10:20"
    target-branch: main
    pull-request-branch-name:
      separator: "-"

    # reviewers:
    #   - "MRRSoft/znode-base-maintainers"

  - package-ecosystem: nuget
    directory: "statenode/APIGateways/Znode.Engine.APIGateways/"
    schedule:
      interval: "daily"
      time: "10:20"
    target-branch: main
    pull-request-branch-name:
      separator: "-"
    
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "10:20"
    target-branch: main
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
