name: now its time
on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: for running commands
        run: ls -ltrh
        
